Add definition for PVC Base and ECS cluster on AWS IaaS
cloudera-labs/cloudera-deploy pull request #143
Opened 2024-06-04 10:36 UTC by jimright

2024-06-04 15:13 UTC, wmudge requested changes

2024-06-04 15:13 UTC, wmudge commented on private-cloud/ecs/aws-iaas/roles/cluster_reqs/vars/main.yml
> +---
License...

2024-06-04 15:13 UTC, wmudge commented on private-cloud/ecs/aws-iaas/roles/krb_file_ticket_cache/defaults/main.yml
> +---
License...

2024-06-04 15:13 UTC, wmudge commented on private-cloud/ecs/aws-iaas/roles/cluster_reqs/tests/test.yml
> +---
License...

2024-06-04 15:13 UTC, wmudge commented on private-cloud/ecs/aws-iaas/roles/cluster_reqs/tests/inventory
> +localhost
License...

2024-06-04 15:13 UTC, wmudge commented on private-cloud/ecs/aws-iaas/roles/cluster_reqs/meta/main.yml
> +galaxy_info:
License...

2024-06-04 15:13 UTC, wmudge commented on private-cloud/ecs/aws-iaas/roles/cluster_reqs/defaults/main.yml
> +---
License...

2024-06-04 15:13 UTC, wmudge commented on private-cloud/ecs/aws-iaas/roles/krb_file_ticket_cache/handlers/main.yml
> +---
License...

2024-06-04 15:13 UTC, wmudge commented on private-cloud/ecs/aws-iaas/roles/krb_file_ticket_cache/tasks/main.yml
> +---
License

2024-06-05 09:07 UTC, jimright commented on private-cloud/ecs/aws-iaas/roles/cluster_reqs/meta/main.yml
> +galaxy_info:
Done in [85561d5](https://github.com/cloudera-labs/cloudera-deploy/pull/143/commits/85561d5db6137299e7e25d323b5761ba600d42e4)

2024-06-05 09:07 UTC, jimright commented on private-cloud/ecs/aws-iaas/roles/cluster_reqs/vars/main.yml
> +---
Done in [85561d5](https://github.com/cloudera-labs/cloudera-deploy/pull/143/commits/85561d5db6137299e7e25d323b5761ba600d42e4)

2024-06-05 09:07 UTC, jimright commented on private-cloud/ecs/aws-iaas/roles/krb_file_ticket_cache/defaults/main.yml
> +---
Done in [85561d5](https://github.com/cloudera-labs/cloudera-deploy/pull/143/commits/85561d5db6137299e7e25d323b5761ba600d42e4)

2024-06-05 09:07 UTC, jimright commented on private-cloud/ecs/aws-iaas/roles/cluster_reqs/tests/test.yml
> +---
Done in [85561d5](https://github.com/cloudera-labs/cloudera-deploy/pull/143/commits/85561d5db6137299e7e25d323b5761ba600d42e4)

2024-06-05 09:07 UTC, jimright commented on private-cloud/ecs/aws-iaas/roles/cluster_reqs/defaults/main.yml
> +---
Done in [85561d5](https://github.com/cloudera-labs/cloudera-deploy/pull/143/commits/85561d5db6137299e7e25d323b5761ba600d42e4)

2024-06-05 09:07 UTC, jimright commented on private-cloud/ecs/aws-iaas/roles/krb_file_ticket_cache/tasks/main.yml
> +---
Done in [85561d5](https://github.com/cloudera-labs/cloudera-deploy/pull/143/commits/85561d5db6137299e7e25d323b5761ba600d42e4)

2024-06-05 13:55 UTC, rsuplina commented
Tested the deployment, ✅ "works on my Machine"

2024-06-05 17:44 UTC, clevesque commented
a few notes on this example:
Can we avoid hardcoding instance type, instance counts, disk sizes/types and ami types inside the terraform config files? Would like to have the option  parameterize those values and pass in from definition.yml
Would like to use a ElasticIP on the bastion, instead of transient public IP.
ty

2024-06-10 14:30 UTC, wmudge approved these changes

2024-06-10 14:31 UTC, merged