Add new example - sandbox-aws with AWS full spec
cloudera-labs/cloudera-deploy pull request #48
Opened 2021-07-20 15:48 UTC by cmperro

2021-07-21 12:15 UTC, cmperro reviewed
should be infra_region

2021-07-21 12:23 UTC, Chaffelson requested changes

2021-07-21 12:23 UTC, Chaffelson commented on examples/sandbox-aws/definition.yml
> +region: us-east-1 #CSP region for infra
infra_region

2021-07-21 12:23 UTC, Chaffelson commented on examples/sandbox-aws/definition.yml
> +  name: chpe-od-2 #Override OpDB name - default is <name_prefix>-od
opdb:
  definitions:
    - name: foo
    - name: bar

2021-07-21 12:23 UTC, Chaffelson commented on examples/sandbox-aws/definition.yml
> +dw: #No current configs can be set here (yet)
include df

2021-10-29 18:10 UTC, wmudge approved these changes

2021-10-29 18:10 UTC, merged